services:
  auth-postgres:
    image: postgres:16-alpine
    container_name: auth-service-postgres
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_USERNAME -d auth_db"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - internal

  user-postgres:
    image: postgres:16-alpine
    container_name: user-service-postgres
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - user_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_USERNAME -d user_db"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - internal

  order-postgres:
    image: postgres:16-alpine
    container_name: order-service-postgres
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - order_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_USERNAME -d order_db"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - internal

  redis:
    image: redis:7.4-alpine
    container_name: user-service-redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - internal

  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    healthcheck:
      test: [ "CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list" ]
      interval: 10s
      timeout: 10s
      retries: 10
    networks:
      - internal

  payment-mongo:
    image: mongo:7
    container_name: payment-service-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - payment_mongo_data:/data/db
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - internal

  auth-service:
    build:
      context: ../auth-service
      dockerfile: Dockerfile
    container_name: auth-service-app
    depends_on:
      auth-postgres:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_URL: jdbc:postgresql://auth-postgres:5432/auth_db
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - internal

  user-service:
    build:
      context: ../user-service
      dockerfile: Dockerfile
    container_name: user-service-app
    depends_on:
      user-postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_URL: jdbc:postgresql://user-postgres:5432/user_db
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      INTERNAL_SECRET: ${INTERNAL_SECRET}
    networks:
      - internal

  order-service:
    build:
      context: ../order-service
      dockerfile: Dockerfile
    container_name: order-service-app
    depends_on:
      order-postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_URL: jdbc:postgresql://order-postgres:5432/order_db
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      USER_SERVICE_URL: ${USER_SERVICE_URL}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
    networks:
      - internal

  payment-service:
    build:
      context: ../payment-service
      dockerfile: Dockerfile
    container_name: payment-service-app
    depends_on:
      payment-mongo:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      MONGO_URI: ${MONGO_URI}
      MONGO_DATABASE: ${MONGO_DATABASE}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      AUTH_SERVICE_URL: ${AUTH_SERVICE_URL}
      RANDOM_API_URL: ${RANDOM_API_URL}
    networks:
      - internal

  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-gateway-app
    depends_on:
      - auth-service
      - user-service
      - order-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      AUTH_SERVICE_URL: ${AUTH_SERVICE_URL}
      USER_SERVICE_URL: ${USER_SERVICE_URL}
      ORDER_SERVICE_URL: ${ORDER_SERVICE_URL}
      PAYMENT_SERVICE_URL: ${PAYMENT_SERVICE_URL}
      INTERNAL_SECRET: ${INTERNAL_SECRET}
    ports:
      - "8080:8080"
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  auth_postgres_data:
  user_postgres_data:
  order_postgres_data:
  payment_mongo_data: